### ISSUE TITLE
未来会像cf better一样提供模板吗

### ISSUE THREAD

**Issue by PXxia** [CuiZhenhang/better-luogu-user-practice#2]
rt

**Comment by CuiZhenhang** [comment]
不打算提供模板。
本项目的主要目的是帮助查看自己和他人的练习情况。对于编写代码，不打算提供帮助。

不过，显示用户个人介绍只是顺手做的小功能，其实有点偏离初衷。但毕竟修改的是用户主页，而且只是把洛谷隐藏的东西取消隐藏，几乎没有负面影响。
